### ISSUE TITLE
Stuck on Apple Logo after boot

### ISSUE THREAD

**Issue by Ventura132** [MumetNgoding/Hackintosh-DELL-Vostro-5468#1]
#Hallo, thank you for your EFI folder.
##I have same machine as yours and already put the EFI folder in my EFI partition. 
##The issue is after boot, loading is stuck on apple logo progress. How to fix this sir ?

**Comment by MumetNgoding** [comment]
add -v on boot-args, and show to me.
btw are u read our configuration? like unlock cfg, etc?
because, the same machine is not necessarily the same configuration.

**Comment by Ventura132** [comment]
i forgot to take a picture but the log is stuck at # Appleintellpssi2ccontroller servicematchingtimersubr......
sure, i already unlock CFG, bios setting same as your mention.
but i have Dell vostro 5468 too, the different is only at RAM. Mine is 12GB

i will check it again tommorow, tidur dulu bang jangan begadang :))

**Comment by MumetNgoding** [comment]
okayyy

**Comment by Ventura132** [comment]
![PXL_20230209_094814900](https://user-images.githubusercontent.com/124806573/217705630-01171f86-0bde-4e97-b8a5-b4ea84ce3015.jpg)
Here for the log sir...

**Comment by MumetNgoding** [comment]
try use this [EFI](https://olarila.com/files/OPENCORE1/EFI.Opencore.NoteBook.KabyLake.zip) .
and after success booting try to fix bugs one by one, i think found problem about GPI0.

**Comment by Ventura132** [comment]
Yes sir... I have success booting with EFI from olarila.
I just want to try your EFI, i think your EFI is the best because we hve same laptop... 

I will try to check agai about CFG Lock..

**Comment by MumetNgoding** [comment]
okay, try to fix bug one by one. see commit and docs for more information.

**Comment by MumetNgoding** [comment]
> 

try new DSDT and confirm to me if works.

**Comment by Ventura132** [comment]
Should i download from the Code (Download zip) or the lates realese sir ?

Download from code getting kernel panic like this
![PXL_20230210_150738144](https://user-images.githubusercontent.com/124806573/218036915-39f23e9c-c397-4ccd-b735-6ddccc768e3d.jpg)

**Comment by MumetNgoding** [comment]
download as zip, don't from release.
u try my efi or only use dsdt?

**Comment by Ventura132** [comment]
Yes sir, downloaded from 'as zip'.
All your efi sir here my step :
1. Download as zip
2. Extract and there is 3 folders (BOOT, OC & Screenshoot)
3. Copy BOOT & OC folders to my EFI folder on my USB. 
4. Add -v on config.plist
5. Boot from USB

Get the kernel panic, like i attached.

**Comment by MumetNgoding** [comment]
> Yes sir, downloaded from 'as zip'. All your efi sir here my step :
> 
> 1. Download as zip
> 2. Extract and there is 3 folders (BOOT, OC & Screenshoot)
> 3. Copy BOOT & OC folders to my EFI folder on my USB.
> 4. Add -v on config.plist
> 5. Boot from USB
> 
> Get the kernel panic, like i attached.

try use EFI from olarila, after success install try one by one, like add kext, dsdt, ane i think u can see where problem.

**Comment by Ventura132** [comment]
can i mix EFI form Olarila with DSDTetc., form your ACPI ?

**Comment by Ventura132** [comment]
can i mix EFI from Olarila with DSDT etc., form your ACPI ?

**Comment by MumetNgoding** [comment]
> can i mix EFI from Olarila with DSDT etc., form your ACPI ?

sure, with ur knowledge.

**Comment by Ventura132** [comment]
i think the problem is about using 
- IntelBluetoothFirmware.kext
- IntelBTPatcher.kext
- BlueToolFixup.kext

without this kext i can boot normal. So, how to fix my bluetooh ?

**Comment by MumetNgoding** [comment]
dont use IntelBTParcher.kext, only user BluetoolFixup and IntelBluetoothFirmware (to load firmware).
clean snapshoot and boot. voila !

**Comment by Ventura132** [comment]
Still the same. Did u change your wifi card ?

**Comment by MumetNgoding** [comment]
no i use default. 
whats macos u installed? if u not use bt.kext can boot?

**Comment by Ventura132** [comment]
latest Ventura 13.2 using EFI olarila i can boot (without bt.kext) 
if bt.kext added, i got kernel panic.

btw my touchpad also didn't work.

**Comment by MumetNgoding** [comment]
already installed?
pm me on telegram. @HafidzRadhival 
i will help u if im free. thanks

**Comment by Ventura132** [comment]
yes sir... already installed.
but BT and Touchpad doesn't work...
okay.. thanks sir

**Comment by MumetNgoding** [comment]
> yes sir... already installed. but BT and Touchpad doesn't work... okay.. thanks sir

try again with my EFI.

**Comment by Ventura132** [comment]
Can boot but without themes.. also wifi don't work.
Are yapu back to OC 0.7.7 ??
